name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Set up virtual environment
        run: ./setup_venv.sh
      - name: Activate virtual environment
        run: source icesee-env/bin/activate
        shell: bash
      - name: Install ICESEE
        run: make install
      - name: Run tests
        run: python -m ICESEE.applications.icepack_model.examples.synthetic_ice_stream.run_da_icepack