physical-parameters:
  # Domain parameters
  Lx: 640e3      # (m) Domain length along ice flow (640 km from paper)
  Ly: 80e3       # (m) Domain width across ice flow (80 km from paper)
  nx: 200        # Number of elements in x-direction (approximates 27,000 elements with varying resolution)
  ny: 50         # Number of elements in y-direction (adjusted for 500 m to 10 km resolution)

modeling-parameters:
  # Model parameters
  num_years: 2          # Number of years to run the model (30-year assimilation period from paper)
  tinitial: 0.0           # Initial time
  timesteps_per_year: 0.1 # Number of timesteps per year (monthly for stability in SSA)

  example_name: "ISMIP_Choi"  # Must have added this to the ISSM directory
  ParamFile: "Mismip2.par" # Parameter file for ISSM-DART setup
  devmode: False            # ISSM development mode 
  hpcmode: False          # True - High-performance computing mode, False - local machine
  use_reference_data: True  # Use reference data for transient steady state
  reference_data_dir: "data" # Directory for reference data
  reference_data: "Transient_steadystate2.mat" # Reference data for transient steady state: only used if use_reference_data is True
  steps: 6                 # Increased steps for finer time integration
  verbose: True              # Enable verbosity for debugging

enkf-parameters:
  # Ensemble Kalman Filter parameters
  Nens: 50                      # Number of ensemble members (paper uses 50)
  freq_obs: 0.5                 # Frequency of observations (annual, as per paper)
  obs_max_time: 2             # Maximum time for observations (30 years)
  obs_start_time: 0.4            # Start time for observations (start of simulation)

  generate_synthetic_obs: 1  # Generate synthetic observations for testing
  generate_true_state:    0  # Generate true state for synthetic observations
  generate_nurged_state:  0  # Generate nudged state for synthetic observations

  num_state_vars: 1             # State variables: ice thickness (H), velocities (u, v)
  num_param_vars: 2             # Parameter variables: friction coefficient (C), bed topography (B)
  vec_inputs: ['Thickness','bed','coefficient'] # State vector inputs (ice thickness and velocities)
  observed_params: ['bed','coefficient']   # Parameters to estimate (friction coefficient, bed topography)

  # Statistical parameters
  sig_obs: [4, 5, 2]          # Observation error std dev: 5 m for H, 10 m/yr for Vx, Vy (paper)
  sig_Q: [2, 1.0, 1.0]          # Process noise std dev (adjusted for H, Vx, Vy)
  length_scale: [30,30,30]               # Length scale for covariance (5 km for friction, per paper)
  
  seed: 1                       # Seed for random number generator
  inflation_factor: 1.10        # Inflation factor (optimal range 1.10–1.18 from paper)
  localization_flag: False       # Enable localization (paper uses 4–8 km radius)
  localization_radius: 6        # Localization radius in km (midpoint of 4–8 km)

  # Estimation flags
  joint_estimation: True        # Enable joint state and parameter estimation
  parameter_estimation: True    # Enable parameter estimation

  # Nudged parameters
  h_nurge_ic: 50                # Nudged increment for initial thickness (reduced for stability)
  u_nurge_ic: 0                 # Nudged increment for initial velocity
  nurged_entries_percentage: 0.05 # Percentage of nudged entries (reduced for finer mesh)

  # EnKF model parameters
  model_name: "issm"            # Model name
  filter_type: "EnKF"           # Filter type: EnKF (Ensemble Kalman Filter)
  parallel_flag: "MPI_model"    # Parallel flag
  n_modeltasks: 4               # Number of model tasks (increased for larger domain)
  commandlinerun: "True"        # Command line run flag
  execution_flag: 2             # Even distribution of problem size
  model_nprocs: 2               # Number of processors for MPI (increased for efficiency)
  data_path: _modelrun_datasets