physical-parameters:
  # Domain parameters
  Lx: 50e2        # (m)
  Ly: 12e2        # (m)
  nx: 16          # number of elements in the x-direction
  ny: 10          # number of elements in the y-direction
  degree: 2       # degree of the polynomial basis functions

  # Bedrock slopes 
  b_in: 200       # (m) above sea level at the inflow
  b_out: -400     # (m) at the terminus

  # Surface Elevation
  s_in: 850       # (m)
  s_out: 50       # (m)

  # Guess for initial velocity
  u_in:  20       # (m/yr)
  u_out: 2400     # (m/yr)

modeling-parameters:
  # Lorenz96 Model parameters
  sigma: 10.0            
  beta: 8.0/3.0 
  rho: 28.0  
  dt: 0.01                 
  num_years: 10          # number of years to run the model
  timesteps_per_year: 2   # number of timesteps per year

enkf-parameters:
  # Ensemble Kalman Filter parameters
  Nens: 30                # number of ensemble members
  m_obs: 10               # number of observations
  freq_obs: 0.2           # frequency of observations

  num_state_vars: 3       # number of state variables 

  # Statistical parameters
  sig_model: 0.1          # model error standard deviation
  sig_obs: 0.01           # observation error standard deviation
  sig_Q: 0.01             # process noise standard deviation

  seed: 1                 # seed for random number generator
  inflation_factor: 1.0          # inflation factor

  # enkf model parameters
  model_name: "lorenz96"               # name of the model
  filter_type: "EnRSKF"               # name of the filter: EnKF, DEnKF, EnTKF, EnRSKF
  parallel_flag: "Serial"             # parallel flag: Serial, MPI
  commandlinerun: "True"              # command line run flag: True, False
 
