parameters:
  A: 4e-26
  year: 31536000  # seconds in a year
  n: 3
  C: 3e6
  rho_i: 900
  rho_w: 1000
  g: 9.8
  accum: 0.65
  facemelt: 5

  # Grid parameters
  NT: 1
  TF: 31536000  # 1 year in seconds
  N1: 40
  N2: 10
  sigGZ: 0.97
  transient: 0
  tcurrent: 1

  # Bed parameters
  xsill: 50000  # in meters
  sillamp: 500
  sillsmooth: 1e-5

  # EnKF parameters
  inflation: 1.0
  assim: false
