physical-parameters:
  # Domain parameters
  Lx: 50e2        # (m)
  Ly: 12e2        # (m)
  nx: 12          # number of elements in the x-direction
  ny: 8          # number of elements in the y-direction
  degree: 2       # degree of the polynomial basis functions

  # Bedrock slopes 
  b_in: 200       # (m) above sea level at the inflow
  b_out: -400     # (m) at the terminus

  # Surface Elevation
  s_in: 850       # (m)
  s_out: 50       # (m)

  # Guess for initial velocity
  u_in:  20       # (m/yr)
  u_out: 2400     # (m/yr)

modeling-parameters:
  # Model parameters
  T: 255.0                # (K) temperature
  a_in: 1.7               # accumulation rate at the inflow
  da:   -2.7              # change of accumulation rate
  a_in_p: 1.87            # nurged accumulation rate at the inflow
  da_p: -2.88            # nurged change of accumulation rate
  num_years: 100          # number of years to run the model
  timesteps_per_year: 2   # number of timesteps per year

enkf-parameters:
  # Ensemble Kalman Filter parameters
  Nens: 30                      # number of ensemble members
  freq_obs: 5                 # frequency of observations
  obs_max_time: 40               # maximum time for observations
  obs_start_time: 5        

  num_state_vars: 3       # number of state variables  [h,u,v] in [h,u,v,smb]
  num_param_vars: 1       # number of parameter variables [smb] in [h,u,v,smb]
  # Statistical parameters
  sig_model: 0.01          # model error standard deviation
  sig_obs: 0.25           # observation error standard deviation
  sig_Q: 0.1            # process noise standard deviation

  seed: 1                 # seed for random number generator
  inflation_factor: 1.02          # inflation factor
  localization_flag: True  # localization flag: True, False
    
  # estimation flags
  joint_estimation: True  # joint estimation flag: True, False
  state_estimation: False  # state estimation flag: True, False
  parameter_estimation: False # parameter estimation flag: True, False

  # nurged parameters
  h_nurge_ic: 100.0         # nurged increment for initial thickness
  u_nurge_ic: 0.0         # nurged increment for initial velocity
  nurged_entries: 150     # number of nurged entries

  # enkf model parameters
  model_name: "icepack"               # name of the model
  model_solver: "solver_weertman"     # name of the solver
  filter_type: "EnKF"          # name of the filter: EnKF, DEnKF, EnTKF EnRSKF
  parallel_flag: "serial"             # parallel flag: Serial, MPI
  commandlinerun: "True"              # command line run flag: True, False
 
